# theme = "catppuccin_latte"
# theme = "catppuccin_frappe"
# theme = "catppuccin_"
# theme = "rose_pine_moon"
#theme = "aura"
# theme = "carbon"

# theme = "rose_pine"
# ttheme = "dracula"
theme = "tokyonight"
# theme = "ayu_mirage"
# theme = "onelight"

# theme = "tokyoday"
[editor]
auto-save	= true
auto-format	= true
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
enable = true
display-inlay-hints	= true

[editor.indent-guides]
render = false
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

[keys.normal]
tab = ":format"
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
X = ["extend_line_up", "extend_to_line_bounds"]
"ret" = "goto_word"

[keys.normal.space]
tab = "goto_last_accessed_file"

